### ISSUE TITLE
`FrameSimulator` for noisy circuits in Python

### ISSUE THREAD

**Issue by Lolcroc** [quantumlib/Stim#135]
Samplers use Pauli frames to efficiently handle noisy circuits behind the scenes, but hide this information in the Python API. It would be nice to explicitly show this information through a Pauli frame simulator for noisy circuits that;

1. Tells you which measurements in a `Circuit` (if any) may be flipped with corresponding pmf. This functionality partly exists as `detector_error_model`, except that detectors are restricted to deterministic outcomes in the noiseless circuit.
2. The probabilistic Pauli frame at the end of the circuit (or at custom markers defined in the circuit).

**Comment by Strilanc** [comment]
> [Have a mode that returns the] Pauli frame at the end of the circuit

This is an interesting idea. Reporting frame changes to measurement results is already a thing in the command line tool (passing the `--frame0` flag in sampling mode skips computing the reference sample by just setting it to 0, meaning the frame changes are returned directly instead of being xored against a reference). Exposing that functionality to python as well makes sense.

I'm hesitant to return the entire frame at the end of the circuit (IXYZ for each qubit). My reasoning is that this features puts the "simulation side" of a circuit into competition with the "sampling side". For example, to get maximum information when simulating you'd have to omit measurements at the end of the circuit (since measurements insert Z errors into the Pauli frame with 50% probability, totally randomizing that information) but to get maximum information when sampling you'd have to include measurements at the end of the circuit. I don't want to put Stim in a design space where methods generating stim circuits have an "if simulating produce this circuit otherwise produce that circuit" flag.

> [Have a mode that] Tells you which measurements [...] may be flipped. [...] detectors are restricted to deterministic outcomes in the noiseless circuit

You can bypass the deterministic limitation by passing `allow_gauge_detectors=True` as an argument to the `detector_error_model` method. If you accompanied every measurement result in the circuit with its own personal `Detector` annotation, and passed that argument, you would get an output equivalent to what you're asking for.

That being said, the performance of the error analysis step and the usefulness of the output will both be significantly worse than in the case of proper locally-sensitive detectors. For example, in the surface code, a bit flip on a data qubit as it is initialized will be interpreted as an error that flips every single Z stabilizer measurement involving that data qubit until the end of time. In a thousand round circuit, It will look like an error with thousands of symptoms. Working with such large errors will slow down the analysis and make the output cumbersome to work with. Also it will prevent loop folding of repeat blocks from succeeding, which is another large slowdown to the analysis.

Given that there is a workaround to achieve this functionality, and given that I expect the output to be poor quality and the performance to be terrible without architectural changes to the error analysis, I currently don't intend to add "compute a measurement error model" functionality as a directly supported feature of stim.

If you think this feature is compelling, I recommend implementing the "gauge detector for each measrement" workaround I mentioned. Make it available to others (e.g. as a pip package or just as code on github), and if lots of people like it then I'm open to merging it into stim itself.

**Comment by Strilanc** [comment]
To summarize:

- I will add some equivalent of `--frame0` to the python API.
- I won't add a "return full Pauli frame at end of circuit" option. (In the future perhaps I might expose the frame simulator in a way similar to how the tableau simulator is exposed, allowing the tableau to be checked at any time. That would more than cover this. But not on the TODO list at the moment.)
- I won't add a "do error analysis but for measurements" option.

**Comment by Lolcroc** [comment]
Coming back to this issue, in case anyone is wondering how to do this. One can invoke a stabilizer version of the [Choi–Jamiołkowski isomorphism](https://en.wikipedia.org/wiki/Choi%E2%80%93Jamio%C5%82kowski_isomorphism) to extract Pauli frames for arbitrary circuits with STIM (under arbitrary input, since we are characterizing a channel). The following script is a short example:

```python
"""
Example of using Choi-Jamiołkowski isomorphism

A is the system under investigation, with qubits 0, 1
B is the ancillary system with the same size as A, with qubits 2, 3

A and B begin with a maximally entangled state (essentially 2 bell pairs on 0-2 and 1-3)

Now the trick is to do the noisy circuit on A (as asual), and to do a noiseless copy on B.
One can show that measurement of the choi state stabilizers will only have some of the signs
flipped, according to how and where the noise was applied.

This information is condensed in STIMs detector error model.
It is trivial to map the information of detectors to Pauli errors (see below).
"""

circuit = stim.Circuit("""
    # Creat a Choi state between A and B
    H 0 1
    CX 0 2 1 3

    # Apply a Bell circuit (example) on A with noise
    H 0
    DEPOLARIZE1(0.1) 0
    CX 0 1
    DEPOLARIZE2(0.1) 0 1

    # Apply the same circuit on B without the noise
    H 2
    CX 2 3

    # Extract errors by measuring the Choi state stabilizers (essentially Bell stabilizers)
    # Every pair anticommutes with either X or Z on the corresponding qubit of A
    # E.g. if X0*X2 and Z0*Z2 trigger, we have a Z error on 0 (flips X0*X2) and an X error on 0 (flips Z0*Z2)
    # hence in total we have a Y error on 0.
    MPP X0*X2 Z0*Z2 X1*X3 Z1*Z3
    DETECTOR rec[-4] # Measures X0*X2, i.e. this detector corresponds to a Z error on 0
    DETECTOR rec[-3] # Measures Z0*Z2, i.e. this detector corresponds to a X error on 0
    DETECTOR rec[-2] # Measures X1*X3, i.e. this detector corresponds to a Z error on 1
    DETECTOR rec[-1] # Measures Z1*Z3, i.e. this detector corresponds to a X error on 0
""")
model = circuit.detector_error_model()
print(model)
```
