### ISSUE TITLE
Upload built distribution to PyPI

### ISSUE THREAD

**Issue by oscarhiggott** [quantumlib/Stim#139]
Thank you for creating this very useful package. Currently only the source distribution is uploaded to PyPI, which leads to long pip installation times. To speed this up, it would be nice if the built distribution could also be uploaded to PyPI for the most common platforms.

**Comment by Strilanc** [comment]
This is definitely something I would like to do. The problem is that I am very wary of doing it, because it would be *so easy* to accidentally include AVX instructions that are not supported across enough machines, and I could easily never know something was wrong.

I will forward this issue along to the internal person who did the work for qsim, to try to entice them to do the same for stim.

**Comment by Strilanc** [comment]
This was done for 1.7
