### ISSUE TITLE
Subprocess error  when `pip install stimcirq`

### ISSUE THREAD

**Issue by inmzhang123** [quantumlib/Stim#214]
![1648468628(1)](https://user-images.githubusercontent.com/61700160/160393231-6fbf51a5-1548-4dd0-9bcb-6134893fd564.png)

**Comment by Strilanc** [comment]
Could you print what python's [sys.getdefaultencoding()](https://docs.python.org/3/library/sys.html#sys.getdefaultencoding) says your system's default encoding is? It looks like it's expecting some chinese-specific character encoding called GBK instead of UTF8?

I suspect I can fix this by replacing `with open('README.md') as f:` with `with open('README.md', encoding="utf-8") as f:` in `setup.py`, but in the meantime you should be able to work around the issue by changing your python' default encoding to UTF-8 (which has become so ubiquitous that it's kind of expected; I wouldn't be surprised if you run into similar issues a lot).

**Comment by inmzhang123** [comment]
> Could you print what python's [sys.getdefaultencoding()](https://docs.python.org/3/library/sys.html#sys.getdefaultencoding) says your system's default encoding is? It looks like it's expecting some chinese-specific character encoding called GBK instead of UTF8?
> 
> I suspect I can fix this by replacing `with open('README.md') as f:` with `with open('README.md', encoding="utf-8") as f:` in `setup.py`, but in the meantime you should be able to work around the issue by changing your python' default encoding to UTF-8 (which has become so ubiquitous that it's kind of expected; I wouldn't be surprised if you run into similar issues a lot).

![image](https://user-images.githubusercontent.com/61700160/160512015-d804d9ee-1c02-46b6-87f4-7f6f2b4e3021.png)

It's actually UTF8 by default...

**Comment by Strilanc** [comment]
@inmzhang123 please verify that `pip install stim==1.9.dev1648583208` does not cause this error

**Comment by inmzhang123** [comment]
> @inmzhang123 please verify that `pip install stim==1.9.dev1648583208` works. If not, the error isn't fixed.

Great, it works!
