### ISSUE TITLE
Implement probabilistic reset gates

### ISSUE THREAD

**Issue by viathor** [quantumlib/Stim#463]
Probabilistic reset channel allows one to implement the combined amplitude and phase damping channel when $T_1=T_2$. For example 
```
R(0.36788) 1
```
could be used to realize idle error for gate whose duration equals $T_1=T_2$.

The more general and practical case with $T_1\ge T_2$ can then be implemented by combining probabilistic reset `R(...)` and `Z_ERROR`.

[More context](https://quantumcomputing.stackexchange.com/q/29867/10480)

**Comment by Strilanc** [comment]
Unfortunately, this gate is incompatible with the efficient detection event sampling strategy that stim uses. Any kind of conditional or probabilistic non-Pauli operation breaks the ability to diff against a single reference sample, instead of a number of reference samples exponential in the number of conditional Cliffords.

I do agree this kind of thing would be useful, but it doesn't really fit in the current design. There would need to be huge sweeping changes to make it work, including changes to what annotations are required to be provided by the user in circuits.

Closing as WONTFIX.
