### ISSUE TITLE
Track overall phase?

### ISSUE THREAD

**Issue by amirebrahimi** [quantumlib/Stim#733]
How difficult would it be to add phase tracking to Tableau/simulators as an option (disabled by default)?

**Comment by Strilanc** [comment]
My understanding was that phase tracking made the Hadamard gate have quadratic cost instead of linear cost, so the performance characteristics were quite different and it requires a totally different simulation strategy.

I'm not opposed to adding a simulator that can do it, but I suspect we're talking about a week's or a month's worth of programming work.

**Comment by Strilanc** [comment]
Closing this as "too much work; out of scope; though not opposed"
