### ISSUE TITLE
Incorrect Tableau definition for S and SDAG

### ISSUE THREAD

**Issue by lag47** [quantumlib/Stim#819]
In `src/stim/gates/gate_data_period_4.cc` the S gate is defined as taking X to +Y and Z to +Z while SDAG is defined as taking X to -Y and Z to +Z

However, with the standard unitary matrix definition of S as [1 0; 0 i], you can compute that these definitions should be swapped.
S^-1 X S = -Y
S^-1 Z S = Z

Sdag ^-1 X Sdag = Y
Sdag ^-1 Z Sdag = Z

**Comment by Strilanc** [comment]
The conjugation of P by U is computed as U P U^-1, not as U^-1 P U.

The tableau entry is intended to represent "if I have P before the gate U in a circuit, what is the equivalent P2 after the gate U in the circuit?". You can verify that the kickback from a Y gate after an S gate undoes the kickback from an X gate before an S gate. Thus S performs X->Y, not X->-Y.


[Circuit:](https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C%22H%22%5D%2C%5B%22X%22%2C%22%E2%80%A2%22%5D%2C%5B1%2C1%2C%22H%22%5D%2C%5B1%2C%22X%22%2C%22%E2%80%A2%22%5D%2C%5B1%2C%22Z%5E%C2%BD%22%5D%2C%5B1%2C%22Y%22%2C%22%E2%80%A2%22%5D%2C%5B1%2C1%2C%22H%22%5D%2C%5B1%2C1%2C%22Chance%22%5D%5D%7D)

![image](https://github.com/user-attachments/assets/bbfa9824-dbd7-4a23-b8e7-13674431ed70)

If you try Y->X across S you find that the kickback is not cancelled out, instead it turns into a deterministic flip of the control meaning the sign is -1 so Y->-X instead of Y->X:

![image](https://github.com/user-attachments/assets/c1c28802-04ac-4b7e-af5c-0c8cf1c3c2ff)

**Comment by lag47** [comment]
In that case, I believe you need to fix the documentation for the `__call__` method on the `stim.Tableau` class. An an excerpt of the documentation

"The conjugation of P by C is equal to C**-1 * P * C. If P is a Pauli product before C, then P2 = C**-1 * P * C is an equivalent Pauli product after C."

This documentation is defined in `src/stim/stabilizers/tableau.pybind.cc` at line 1886.
